// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoEnade.Repository;

namespace ProjetoEnade.Migrations
{
    [DbContext(typeof(EnadeDbContext))]
    [Migration("20211201201816_ImagesMigrationss")]
    partial class ImagesMigrationss
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoEnade.Models.CursoDisciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDisciplina");

                    b.ToTable("CursoDisciplina");
                });

            modelBuilder.Entity("ProjetoEnade.Models.Cursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("ProjetoEnade.Models.Disciplinas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("ProjetoEnade.Models.Provas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("Edicao")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCurso")
                        .IsUnique();

                    b.ToTable("Provas");
                });

            modelBuilder.Entity("ProjetoEnade.Models.QuestaoGabarito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DificuldadeQuestao")
                        .HasColumnType("int");

                    b.Property<string>("Enunciado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EnunciadoImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdProva")
                        .HasColumnType("int");

                    b.Property<string>("RespostaA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RespostaAImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RespostaB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RespostaBImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RespostaC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RespostaCImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RespostaCorreta")
                        .HasColumnType("int");

                    b.Property<string>("RespostaD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RespostaDImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RespostaDissertativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespostaE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RespostaEImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TipoProva")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProva");

                    b.ToTable("QuestaoGabarito");
                });

            modelBuilder.Entity("ProjetoEnade.Models.QuestoesDisciplinas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.Property<int>("IdQuestao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDisciplina");

                    b.HasIndex("IdQuestao");

                    b.ToTable("QuestoesDisciplinas");
                });

            modelBuilder.Entity("ProjetoEnade.Models.CursoDisciplina", b =>
                {
                    b.HasOne("ProjetoEnade.Models.Cursos", "Curso")
                        .WithMany("CursoDisciplina")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEnade.Models.Disciplinas", "Disciplinas")
                        .WithMany("CursoDisciplina")
                        .HasForeignKey("IdDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("ProjetoEnade.Models.Disciplinas", b =>
                {
                    b.HasOne("ProjetoEnade.Models.Cursos", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("ProjetoEnade.Models.Provas", b =>
                {
                    b.HasOne("ProjetoEnade.Models.Cursos", "Cursos")
                        .WithOne("Prova")
                        .HasForeignKey("ProjetoEnade.Models.Provas", "IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("ProjetoEnade.Models.QuestaoGabarito", b =>
                {
                    b.HasOne("ProjetoEnade.Models.Provas", "Provas")
                        .WithMany("QuestoesGabarito")
                        .HasForeignKey("IdProva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provas");
                });

            modelBuilder.Entity("ProjetoEnade.Models.QuestoesDisciplinas", b =>
                {
                    b.HasOne("ProjetoEnade.Models.Disciplinas", "Disciplinas")
                        .WithMany("QuestoesDisciplinas")
                        .HasForeignKey("IdDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEnade.Models.QuestaoGabarito", "Questoes")
                        .WithMany("QuestoesDisciplinas")
                        .HasForeignKey("IdQuestao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplinas");

                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("ProjetoEnade.Models.Cursos", b =>
                {
                    b.Navigation("CursoDisciplina");

                    b.Navigation("Prova");
                });

            modelBuilder.Entity("ProjetoEnade.Models.Disciplinas", b =>
                {
                    b.Navigation("CursoDisciplina");

                    b.Navigation("QuestoesDisciplinas");
                });

            modelBuilder.Entity("ProjetoEnade.Models.Provas", b =>
                {
                    b.Navigation("QuestoesGabarito");
                });

            modelBuilder.Entity("ProjetoEnade.Models.QuestaoGabarito", b =>
                {
                    b.Navigation("QuestoesDisciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
